### ISSUE TITLE
Your `tar` implementation has (potential) resources leaks

### ISSUE THREAD

**Issue by SamuelMarks** [jozu-ai/kitops#378]
Specifically:
https://github.com/jozu-ai/kitops/blob/b95676e/pkg/lib/harness/llm_payload_all.go#L138

Feel free to use my—`Apache-2.0 OR MIT OR CC0`—implementation:
https://github.com/offscale/postgres-version-manager-go/blob/f14c61b/pvm/remote_fetch.go#L99-L167

**Comment by gorkem** [comment]
Thank you for reporting this. I see how it can go wrong. 😒 
We do accept pull requests too 😄 Would you care to send one in?

**Comment by bmicklea** [comment]
I'm going to close this issue as won't fix because we looked at the code and:
1. There is a low chance of resources being leaked
2. If resources were leaked the CLI would need to be running for hours in order for it to be a material issue
3. The longest running command is `kit dev` but even that spins up another binary so it doesn't actually run long at all

Kit CLI frees up all resources whenever it ends a task and most tasks are very short so we'll keep an eye on this but don't see a reason to spend cycles on trying to fix it. If you feel strongly about it @SamuelMarks please create a PR and we'll review.
