### ISSUE TITLE
`kit pack` freezes when Kitfile 'docs' section includes a path to a directory instead of individual file paths

### ISSUE THREAD

**Issue by brett-hodges** [jozu-ai/kitops#620]
**Describe the bug**
Please refer to the attached screenshot below.  The area outlined in green shows the contents of a simple Kitfile.  The area outlined in blue shows that the 'docs' section contains a path element that references a directory named 'artifacts/'. (Individual files in that directory are not specified, as all files are meant to be included if a directory path is specified.)

On my machine, the 'artifacts' directory contains a six image files and one csv files, all of which are small in size.

When I run the kit pack command (outlined in yellow), it stalls with 0 bytes processed (as shown in the area outlined by red).

![Screenshot 2024-11-25 at 9 12 31 AM](https://github.com/user-attachments/assets/b185e281-8b26-4773-b758-f915b006627e)

**To Reproduce**
1. Create a Kitfile like the one shown in the screenshot.
2. Create an 'artifacts' directory in the same directory containing the Kitfile.
3. In the 'artifacts' directory, create a non-empty text file with any name of your choosing.
4. Try to pack the ModelKit using the `kit pack` command.
5. Note that the command hangs.

**Version**
0.4.0 (latest)

**Additional context**

**Comment by amisevsk** [comment]
This bug actually points at _another_ bug with how ignores work; when a path is specified with a trailing slash, it can result in files being erroneously ignored in the pack process. 

Since the file is ignored, the progress bar is never completed (since we never actually write the full expected size). If you disable progress bars (e.g. via `-vvv`), the pack succeeds, though it may not pack all files.
