### ISSUE TITLE
kit pack error

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#81]
**Describe the bug**
When trying to run `kit pack` with the attached Kitfile I get an error:
```
Failed to pack model kit: error resolving /Users/bmicklea/Documents/GitHub: lstat /Users/bmicklea/Documents/GitHub/Users: no such file or directory
```

It looks like it's appending a second `Users` to the path, although that's weird because the path actually has more to it...

[kitfile.txt](https://github.com/jozu-ai/kitops/files/14530215/kitfile.txt)

**To Reproduce**
1. Run `kit pack ./` with the attached kitfile (it'll need to have the .txt extension removed)
2. See error

**Version**
Next

**Comment by amisevsk** [comment]
The _awful_ error message we're printing is hiding quite a few layers in what's actually going wrong here, which range from very simple to fix to design-level questions:

1. First and foremost, we're missing some basic validation of Kitfile fields -- if a Kitfile contains an absolute path (as the sample here does), we should report that as the error rather than trying to process it further.
2. The reason this error is being triggered is because paths in a Kitfile are assumed to be relative to the pack context. For example, if I run
    ```
    kit pack <directory>
    ```
    and have a Kitfile with the model
    ```yaml
    model:
      name: my-model
      path: path/to/some/model
    ```
    we will look for the model in `<directory>/path/to/some/model`. For the sample Kitfile, we're assuming the absolute paths are relative, which leads to strange paths in the error message. This is mentioned in the help text for `kit pack` but should be documented more clearly.
3. Fixing 1 and 2 above would lead to another issue with paths, where we require all parts of a ModelKit to exist within one "parent" directory (the `<directory>` in `kit pack <directory>`). This is necessary to avoid potentially dangerous behavior where packing or unpacking a ModelKit could interact with sensitive files on the system, which we want to prevent. This is also something that should be documented clearly to avoid strange pitfalls.
4. Finally, the Kitfile is attempting to reference a dataset by remote URL, which we currently don't support -- `path` is assumed to refer to a local path to some files we want to include in the ModelKit. I think for practical purposes, storing datasets remotely makes a lot of sense, so maybe it makes sense to extend the `Kitfile` section for datasets to support this explicitly. 

The top few we can (and should) fix fairly easily. The question of how we support remotely stored datasets is potentially another matter.
